### PR TITLE
Reorganize Readline

### LINKED ISSUE #40: Cursor bug when prompt is shifted
# Description
When launching Minishell, if the prompt is misaligned, the cursor does not move to the correct position.
# Steps to reproduce
- Launch program with valgrind
- Write something before the prompt appears
- Rewrite somthing after
# Images

Image

Image

### LINKED ISSUE #68: Reorganize Readline System

### LINKED ISSUE #78: readline print unnecessary newline when path too long
Image

### LINKED ISSUE #79: home and end doesn't/don't/should/would have to/have to/must work on linux
Image ([H = home and [F = end)

### LINKED ISSUE #98: bug when deleting newline at last line of terminal
test case :  (3 bajillion newline till end of the terminal)
echo \ {enter}
{backspace key}

Image

Image

### LINKED ISSUE #105: function to disable quote and backslash checking in readline

### LINKED ISSUE #106: readline doesn't shift properly when going to a previous command with a newline

### LINKED ISSUE #111: Newline in first position when a quote is not closed
Image

### PR DESCRIPTION
**Pull request by SunsetTadpole78**
- fixes #40 
- fixes #68 
- fixes #78 
- fixes #105
- fixes #79 
- fixes #106 
- fixes #98 
- fixes #111

### CODE REVIEW

File: src/ft_readline/initialization.c [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+	if (!data->is_pipe)
+		write(2, prompt, ft_strlen(prompt));
+	data->display_prompt = isatty(STDERR_FILENO);
+	data->offset = data->pos.x - 1;
+	if (data->display_prompt)
+	{
+		data->pos.x += ft_strlen(prompt);
+		data->pos.y += data->pos.x / data->old_tsize.x;
+		data->pos.x -= ft_strlen(prompt)
+			- ft_strlen(ft_getlast_newline((char *)prompt));
```
Comment (Galbio) [inline src/ft_readline/initialization.c:45]:
```suggestion
		data->pos.y += data->pos.x / data->old_tsize.x;
		data->pos.x -= ft_strlen(ft_getlast_newline((char *)prompt));
```

File: src/minishell.c [hunk 2]
```diff
@@ -45,5 +45,5 @@ void	launch(t_list *envp, t_main_envp *imp)
 		imp->input_fd = 0;
 		execute_line(res, &envp, imp);
 	}
-	write(1, "\n", 1);
+	write(STDIN_FILENO, "\n", 1);
```
Comment (Galbio) [inline src/minishell.c:48]: unnecessary change

File: src/ft_readline/special_key/factory.c [hunk 3]
```diff
@@ -31,57 +31,36 @@ static void	on_overwrite(char *sequence)
...
-	main->special_keys = ft_realloc(
-			main->special_keys,
-			sizeof(t_special_key *) * (count + 1),
-			sizeof(t_special_key *) * (count + 2)
-			);
-	main->special_keys[count] = malloc(sizeof(t_special_key));
-	main->special_keys[count]->sequence = sequence;
-	main->special_keys[count]->callback = callback;
-	main->special_keys[count + 1] = NULL;
+	new = malloc(sizeof(t_special_key));
```
Comment (Galbio) [inline src/ft_readline/special_key/factory.c:41]: return in case of NULL

File: src/ft_readline/edition/utils.c [hunk 4]
```diff
@@ -40,10 +40,12 @@ void	update_position(t_readline *data, t_vector2 size,
 void	print_build(char *build)
 {
 	int	i;
+	int	in;
```
Comment (Galbio) [inline src/ft_readline/edition/utils.c:43]: find a better name

File: src/ft_readline/clean/readed.c
Comment (Galbio) [inline src/ft_readline/clean/readed.c:1]: unused file (I'm sure I deleted it in a previous pr)

File: src/ft_readline/cursor/position/stdin.c [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+static int	parse_row_col_from_plain_text(const char *input, int *row, int *col)
+{
+	int	i;
+
+	i = 0;
+	*row = 0;
+	*col = 0;
+	while (input[i] == ' ' || input[i] == '\t')
+		i++;
+	if (!(input[i] >= '0' && input[i] <= '9'))
```
Comment (Galbio) [inline src/ft_readline/cursor/position/stdin.c:24]:
```suggestion
	if (!ft_isdigit(input[i]))
```

**Review by Galbio — CHANGES_REQUESTED** [review]
fix the ctrl w segfault (space then ctrl w)
fix valgrind error (valgrind ./minishell | valgrind ./minishell)  (the second minishell is the one with the error)

File: src/ft_readline/process/converter.c [hunk 6]
```diff
@@ -1,70 +1,70 @@
...
 	int		j;
 
 	j = 0;
-	while (c->c[j])
+	while (c->sequence[j])
 	{
-		(*result)[*i] = c->c[j];
+		(*result)[*i] = c->sequence[j];
 		j++;
 		(*i)++;
```
[the remark this answers is not in the document]
Comment (SunsetTadpole78) [reply src/ft_readline/process/converter.c:53]: no, i use (*result)[*i] in the loop

File: src/ft_readline/extra/raw_mode.c [hunk 7]
```diff
@@ -29,6 +29,8 @@ void	enable_raw_mode(void)
 {
 	struct termios	raw;
 
+	if (!isatty(STDIN_FILENO))
+		return ;
 	old();
```
Comment (Galbio) [inline src/ft_readline/extra/raw_mode.c:34]: find a better name

File: src/ft_readline/process/reader.c [hunk 8]
```diff
@@ -1,23 +1,28 @@
...
 	byte_read = read(STDIN_FILENO, buffer, 4095);
 	if (byte_read == -1)
-		exit(4);
+	{
+		buffer[0] = '\0';
+		return (0);
+	}
 	buffer[byte_read] = '\0';
+	return (1);
+	return (!(buffer[0] == '\0' && !isatty(STDIN_FILENO)));
```
Comment (Galbio) [inline src/ft_readline/process/reader.c:27]: what is the second line for ?

File: src/signals.c
Comment (Galbio) [inline src/signals.c:1]: useless change

**Review by Galbio — CHANGES_REQUESTED** [review]

File: .github/workflows/norminette.yml [hunk 9]
```diff
@@ -21,4 +21,7 @@ jobs:
           pip install norminette
 
       - name: Run Norminette
-        run: norminette || exit 1
+        run: |
+          OUTPUT=$(norminette)
+          echo "$OUTPUT"
+          echo "$OUTPUT" | grep -q "Error" && exit 1 || exit 0
```
Comment (Galbio) [inline .github/workflows/norminette.yml:27]:
```suggestion
        run: norminette | (grep -q "Error" && exit 1 ; exit 0)
```

**Review by Galbio — CHANGES_REQUESTED** [review]

**Review by Galbio — APPROVED** [review]
