### PR TITLE
Fix Bquotes

### LINKED ISSUE #45: bquotes don't work
should fix bquote at some point

### PR DESCRIPTION
**Pull request by Galbio**
- fixes #45

### CODE REVIEW

File: src/init_pipes.c [hunk 1]
```diff
@@ -6,37 +6,58 @@
...
+	t_list		*cmds;
 
 	itab = init_int_tab();
-	commands = NULL;
+	cmds = NULL;
 	while (str[++itab.i])
 	{
+		if ((str[itab.i] == '$') && !itab.backslash && !itab.cur_quote)
+			if (go_to_var_end(str, &itab.i))
+				break ;
```
Comment (SunsetTadpole78) [inline src/init_pipes.c:45]: why double if ?

**Review by SunsetTadpole78 — CHANGES_REQUESTED** [review]

File: src/init_pipes.c (hunk 1 above)
Comment (Galbio) [reply src/init_pipes.c:45]: the first if checks if you encouter a variable, the second if change i to go to the end of the variable (and return 1 if you reached the end of the string)

File: src/builtins/cd.c
[the remark this answers is not in the document]
Comment (SunsetTadpole78) [reply src/builtins/cd.c:1]: ?

**Review by SunsetTadpole78 — CHANGES_REQUESTED** [review]

**Review by SunsetTadpole78 — APPROVED** [review]
